### ISSUE TITLE
Running second time AutoMigrate tries add the columns again

### ISSUE THREAD

**Issue by JoroVSG** [googleapis/go-gorm-spanner#13]
The AutoMigrate method on already existing entities tries to add all the files as columns again
![image](https://github.com/googleapis/go-gorm-spanner/assets/40761072/ecebf48b-d6c1-429d-a67e-29ff3b7332b4)
 As of my knowledge these columns don't exist in the information_schema table in spanner and think the problem comes from the ColumnTypes function of the spannerMigrator because it can't get the meta information of the columns and futher down on the execution it tries to re-create the columns 
![image](https://github.com/googleapis/go-gorm-spanner/assets/40761072/353203de-7177-4f3f-9f46-01912076030d)
![image](https://github.com/googleapis/go-gorm-spanner/assets/40761072/8a525ca1-f2d6-459b-b38b-b24c1b2342b2)

Models are:
```go
type Singer struct {
	Id        string  `gorm:"primaryKey" json:"id"`
	FirstName *string `json:"firstName"`
	LastName  string  `json:"lastName"`
	FullName  string  `gorm:"->;type:STRING(MAX) AS (ARRAY_TO_STRING([FirstName, LastName], \" \")) STORED;" json:"-"`
	Active    bool    `json:"active"`
	Albums    []Album `json:"albums"`
}

type Album struct {
	Id              string     `gorm:"primaryKey" json:"id"`
	Title           string     `json:"title"`
	MarketingBudget *int64     `json:"marketingBudget"`
	ReleaseDate     *time.Time `json:"releaseDate"`
	CoverPicture    []byte     `json:"coverPicture"`
	SingerId        string     `json:"singerId"`
}
```

#### Environment details

  - Programming language: golang
  - OS: win11, macos 14
  - Language runtime version: 1.21
  - Package version: latest

#### Steps to reproduce

  1. Run the AutoMigrate once - works fine
  2. Run the AutoMigrate twice - fails with duplicate column name XXX 

Excepted behaviour is on the second run to migrator to identifies the columns already exist and to skip re-creating them again

Thanks!

**Comment by rahul2393** [comment]
Thanks @JoroVSG for reporting this,will be fixed in next release
