### ISSUE TITLE
Does this driver support POSTGRESQL Dialect?

### ISSUE THREAD

**Issue by newtonnthiga** [googleapis/go-gorm-spanner#82]
I'm testing out different use cases for this driver and I'm curious if it supports the PostgreSQL dialect or just the GoogleSQL Dialect. Seems to me a lot of queries work just fine when the parent database is using GoogleSQL but not when it's using PostgreSQL.

**Comment by olavloite** [comment]
> Looks like I must instead use the pgadapter(https://github.com/GoogleCloudPlatform/pgadapter)? Is that right

Yes, that is correct. If you want to use the PostgreSQL dialect with Spanner in combination with an ORM, then you should use the PostgreSQL ORM implementation in combination with PGAdapter.
