### ISSUE TITLE
How to work with JSON in Gorm + Spanner

### ISSUE THREAD

**Issue by adamovittorio** [googleapis/go-gorm-spanner#92]
Hello, I want to understand how to properly define a Gorm/Spanner model with a JSON field. Looking at the docs, the only thing I could find is this: https://github.com/googleapis/go-gorm-spanner/blob/9ef0ef0b54f51ba3e42a2c898c7ed90cd875b3c0/README.md?plain=1#L85

Now it works, but is it the best and recommended way to do it, and how can I query a specific JSON field using Gorm?

Example code

```go
package models

import "gorm.io/gorm"

type Audit struct {
	gorm.Model
	Service  string `json:"service"`
	Metadata string `json:"metadata"`
}

```

```go
func Audits(c *gin.Context) {
	var audits []models.Audit
	result := database.DB.Find(&audits) // How can I query the audits that have metadata with a specific key-value pair?

	if result.Error != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": result.Error.Error()})

		return
	}

	response := []map[string]interface{}{}

	for _, audit := range audits {
		var metadata map[string]interface{}
		if err := json.Unmarshal([]byte(audit.Metadata), &metadata); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to unmarshal metadata"})

			return
		}

		auditMap := map[string]interface{}{
			"id":        audit.ID,
			"service":   audit.Service,
			"createdAt": audit.CreatedAt,
			"updatedAt": audit.UpdatedAt,
			"deletedAt": audit.DeletedAt,
			"metadata":  metadata,
		}
		response = append(response, auditMap)
	}

	c.JSON(http.StatusOK, gin.H{"data": response})
}

```

**Comment by adamovittorio** [comment]
I can't see that there is no mapping for the JSON type in the dialect implementation. https://github.com/googleapis/go-gorm-spanner/blob/main/spanner.go#L196

Do you have any plans to support JSON, are you open to contributions? I believe that with some guidance, I could add the functionality to this library

**Comment by rahul2393** [comment]
cc: @olavloite

**Comment by rahul2393** [comment]
@adamovittorio Thanks for opening the issue, 
I have added a PR to showcase working with JSON data type, please check if its sufficient for answering your question.

And yes we welcome any contributions, feel free to create Issue/PR https://github.com/googleapis/go-gorm-spanner?tab=readme-ov-file#contributing

**Comment by adamovittorio** [comment]
@rahul2393, thank you very much for the fast resolution! I adjusted my code following the example in #93, which answered my questions on defining the model in gorm+spanner and querying/mutating JSON fields. 🙏
